version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - run: ls
          
workflows:
  welcome:
    jobs:
      - thing
      - build:
    filters:
      branches:
        only: master
