version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - run: ls

  test:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - run: pwd


          
workflows:
  welcome:
    jobs:
      #seem to have to have two jobs in here (or maybe it's the requires), or circle config processing strips off your filter.  wtf
      - build
      - test:
          requires:
            - build
          filters:
            tags:
              only: shmoop