version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - run: ls

  test:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - run: pwd


          
workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master